#!/bin/bash
# (c) Orlando Chamberlain
#
# Export the current state of the repo to a patch that can be applied to the
# kernel tree if you want to build apple-bce in tree.

set -e

KTAG=$1 # e.g. "v6.5", this is the upstream kernel version we take the diff for makefile and kconfig from

if [ -z $KTAG ]; then
	echo "Usage: $0 [upstream kernel tag]"
	exit 1
fi

COMMIT_MSG="apple-bce: init

Import from $(git rev-parse  HEAD)

Should apply to $KTAG.

This is generated by an automated script.
"

SRCDIR=$PWD
TMPDIR=$(mktemp --directory)
cd $TMPDIR
mkdir -p drivers/staging/apple-bce
git init .
curl -s https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/drivers/staging/Kconfig\?h=$KTAG -o drivers/staging/Kconfig
curl -s https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/drivers/staging/Makefile\?h=$KTAG -o drivers/staging/Makefile

git add drivers/staging/Makefile drivers/staging/Kconfig
git commit -m f --author="A script <nobody@t2linux.org>"

echo 'source "drivers/staging/apple-bce/Kconfig"' >> drivers/staging/Kconfig
echo 'obj-$(CONFIG_APPLE_BCE)		+= apple-bce/' >> drivers/staging/Makefile
git add drivers/staging/Makefile drivers/staging/Kconfig

cd drivers/staging/apple-bce
git --git-dir $SRCDIR/.git archive --format tar HEAD | tar -x

# TODO: when vhci and aaudio have seperate CONFIG variables, update this.
sed -i s/obj-m/obj-\$\(CONFIG_APPLE_BCE\)/g Makefile


git add .

git commit -m "$COMMIT_MSG" --author="A script <nobody@t2linux.org>"
git format-patch -o $SRCDIR -n1


